/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedHqRouteImport } from './routes/_authenticated/hq'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSalesEliteRouteImport } from './routes/_authenticated/sales-elite'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as QTokenRouteImport } from './routes/q.$token'
import { Route as AuthenticatedConversationsIndexRouteImport } from './routes/_authenticated/conversations/index'
import { Route as AuthenticatedConversationsConversationIdRouteImport } from './routes/_authenticated/conversations/$conversationId'
import { Route as AuthenticatedExecutiveIndexRouteImport } from './routes/_authenticated/executive/index'
import { Route as AuthenticatedExecutiveWorkerKeyRouteImport } from './routes/_authenticated/executive/$workerKey'
import { Route as AuthenticatedExecutiveAuditRouteImport } from './routes/_authenticated/executive/audit'
import { Route as AuthenticatedExecutiveWorkforceRouteImport } from './routes/_authenticated/executive/workforce'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge/index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads/index'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads/$leadId'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAgencyRouteImport } from './routes/_authenticated/settings/agency'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings/ai'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedSettingsGovernanceRouteImport } from './routes/_authenticated/settings/governance'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsSubscriptionRouteImport } from './routes/_authenticated/settings/subscription'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings/team'
import { Route as AuthenticatedSettingsVoiceRouteImport } from './routes/_authenticated/settings/voice'
import { Route as AuthenticatedSettingsWhatsappRouteImport } from './routes/_authenticated/settings/whatsapp'
import { Route as ApiPublicMeetExecutiveRouteImport } from './routes/api/public/meet-executive'
import { Route as ApiPublicMeetRequestRouteImport } from './routes/api/public/meet-request'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'
import { Route as ApiPublicHealthBuildRouteImport } from './routes/api/public/health/build'
import { Route as ApiPublicHealthOpusProbeRouteImport } from './routes/api/public/health/opus-probe'
import { Route as ApiPublicHooksExecutiveAutonomyRouteImport } from './routes/api/public/hooks/executive-autonomy'
import { Route as ApiPublicHooksTaskEngineRouteImport } from './routes/api/public/hooks/task-engine'
import { Route as ApiPublicPaymentsStripeWebhookRouteImport } from './routes/api/public/payments/stripe-webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicTmpEnvCheckRouteImport } from './routes/api/public/tmp/env-check'
import { Route as ApiPublicTmpFlyIpv6RouteImport } from './routes/api/public/tmp/fly-ipv6'
import { Route as ApiPublicTmpFlyVerifyRouteImport } from './routes/api/public/tmp/fly-verify'
import { Route as ApiPublicVoiceEventsRouteImport } from './routes/api/public/voice/events'
import { Route as ApiPublicVoiceTurnRouteImport } from './routes/api/public/voice/turn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHqRoute = AuthenticatedHqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesEliteRoute = AuthenticatedSalesEliteRouteImport.update({
  id: '/sales-elite',
  path: '/sales-elite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConversationsIndexRoute =
  AuthenticatedConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationsConversationIdRoute =
  AuthenticatedConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecutiveIndexRoute =
  AuthenticatedExecutiveIndexRouteImport.update({
    id: '/executive/',
    path: '/executive/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecutiveWorkerKeyRoute =
  AuthenticatedExecutiveWorkerKeyRouteImport.update({
    id: '/executive/$workerKey',
    path: '/executive/$workerKey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecutiveAuditRoute =
  AuthenticatedExecutiveAuditRouteImport.update({
    id: '/executive/audit',
    path: '/executive/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecutiveWorkforceRoute =
  AuthenticatedExecutiveWorkforceRouteImport.update({
    id: '/executive/workforce',
    path: '/executive/workforce',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAgencyRoute =
  AuthenticatedSettingsAgencyRouteImport.update({
    id: '/agency',
    path: '/agency',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSettingsRouteRoute,
} as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGovernanceRoute =
  AuthenticatedSettingsGovernanceRouteImport.update({
    id: '/governance',
    path: '/governance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSubscriptionRoute =
  AuthenticatedSettingsSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsVoiceRoute =
  AuthenticatedSettingsVoiceRouteImport.update({
    id: '/voice',
    path: '/voice',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsWhatsappRoute =
  AuthenticatedSettingsWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const ApiPublicMeetExecutiveRoute = ApiPublicMeetExecutiveRouteImport.update({
  id: '/api/public/meet-executive',
  path: '/api/public/meet-executive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMeetRequestRoute = ApiPublicMeetRequestRouteImport.update({
  id: '/api/public/meet-request',
  path: '/api/public/meet-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthBuildRoute = ApiPublicHealthBuildRouteImport.update({
  id: '/api/public/health/build',
  path: '/api/public/health/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthOpusProbeRoute =
  ApiPublicHealthOpusProbeRouteImport.update({
    id: '/api/public/health/opus-probe',
    path: '/api/public/health/opus-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExecutiveAutonomyRoute =
  ApiPublicHooksExecutiveAutonomyRouteImport.update({
    id: '/api/public/hooks/executive-autonomy',
    path: '/api/public/hooks/executive-autonomy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTaskEngineRoute =
  ApiPublicHooksTaskEngineRouteImport.update({
    id: '/api/public/hooks/task-engine',
    path: '/api/public/hooks/task-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsStripeWebhookRoute =
  ApiPublicPaymentsStripeWebhookRouteImport.update({
    id: '/api/public/payments/stripe-webhook',
    path: '/api/public/payments/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTmpEnvCheckRoute = ApiPublicTmpEnvCheckRouteImport.update({
  id: '/api/public/tmp/env-check',
  path: '/api/public/tmp/env-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTmpFlyIpv6Route = ApiPublicTmpFlyIpv6RouteImport.update({
  id: '/api/public/tmp/fly-ipv6',
  path: '/api/public/tmp/fly-ipv6',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTmpFlyVerifyRoute = ApiPublicTmpFlyVerifyRouteImport.update({
  id: '/api/public/tmp/fly-verify',
  path: '/api/public/tmp/fly-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceEventsRoute = ApiPublicVoiceEventsRouteImport.update({
  id: '/api/public/voice/events',
  path: '/api/public/voice/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceTurnRoute = ApiPublicVoiceTurnRouteImport.update({
  id: '/api/public/voice/turn',
  path: '/api/public/voice/turn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/meet': typeof MeetRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/hq': typeof AuthenticatedHqRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sales-elite': typeof AuthenticatedSalesEliteRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/join/$token': typeof JoinTokenRoute
  '/q/$token': typeof QTokenRoute
  '/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/executive/$workerKey': typeof AuthenticatedExecutiveWorkerKeyRoute
  '/executive/audit': typeof AuthenticatedExecutiveAuditRoute
  '/executive/workforce': typeof AuthenticatedExecutiveWorkforceRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/settings/agency': typeof AuthenticatedSettingsAgencyRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/governance': typeof AuthenticatedSettingsGovernanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/subscription': typeof AuthenticatedSettingsSubscriptionRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/voice': typeof AuthenticatedSettingsVoiceRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/api/public/meet-executive': typeof ApiPublicMeetExecutiveRoute
  '/api/public/meet-request': typeof ApiPublicMeetRequestRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/executive/': typeof AuthenticatedExecutiveIndexRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/health/build': typeof ApiPublicHealthBuildRoute
  '/api/public/health/opus-probe': typeof ApiPublicHealthOpusProbeRoute
  '/api/public/hooks/executive-autonomy': typeof ApiPublicHooksExecutiveAutonomyRoute
  '/api/public/hooks/task-engine': typeof ApiPublicHooksTaskEngineRoute
  '/api/public/payments/stripe-webhook': typeof ApiPublicPaymentsStripeWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tmp/env-check': typeof ApiPublicTmpEnvCheckRoute
  '/api/public/tmp/fly-ipv6': typeof ApiPublicTmpFlyIpv6Route
  '/api/public/tmp/fly-verify': typeof ApiPublicTmpFlyVerifyRoute
  '/api/public/voice/events': typeof ApiPublicVoiceEventsRoute
  '/api/public/voice/turn': typeof ApiPublicVoiceTurnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/meet': typeof MeetRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/hq': typeof AuthenticatedHqRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sales-elite': typeof AuthenticatedSalesEliteRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/join/$token': typeof JoinTokenRoute
  '/q/$token': typeof QTokenRoute
  '/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/executive/$workerKey': typeof AuthenticatedExecutiveWorkerKeyRoute
  '/executive/audit': typeof AuthenticatedExecutiveAuditRoute
  '/executive/workforce': typeof AuthenticatedExecutiveWorkforceRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/settings/agency': typeof AuthenticatedSettingsAgencyRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/governance': typeof AuthenticatedSettingsGovernanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/subscription': typeof AuthenticatedSettingsSubscriptionRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/voice': typeof AuthenticatedSettingsVoiceRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/api/public/meet-executive': typeof ApiPublicMeetExecutiveRoute
  '/api/public/meet-request': typeof ApiPublicMeetRequestRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/conversations': typeof AuthenticatedConversationsIndexRoute
  '/executive': typeof AuthenticatedExecutiveIndexRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/health/build': typeof ApiPublicHealthBuildRoute
  '/api/public/health/opus-probe': typeof ApiPublicHealthOpusProbeRoute
  '/api/public/hooks/executive-autonomy': typeof ApiPublicHooksExecutiveAutonomyRoute
  '/api/public/hooks/task-engine': typeof ApiPublicHooksTaskEngineRoute
  '/api/public/payments/stripe-webhook': typeof ApiPublicPaymentsStripeWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tmp/env-check': typeof ApiPublicTmpEnvCheckRoute
  '/api/public/tmp/fly-ipv6': typeof ApiPublicTmpFlyIpv6Route
  '/api/public/tmp/fly-verify': typeof ApiPublicTmpFlyVerifyRoute
  '/api/public/voice/events': typeof ApiPublicVoiceEventsRoute
  '/api/public/voice/turn': typeof ApiPublicVoiceTurnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/meet': typeof MeetRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/hq': typeof AuthenticatedHqRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sales-elite': typeof AuthenticatedSalesEliteRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/join/$token': typeof JoinTokenRoute
  '/q/$token': typeof QTokenRoute
  '/_authenticated/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/_authenticated/executive/$workerKey': typeof AuthenticatedExecutiveWorkerKeyRoute
  '/_authenticated/executive/audit': typeof AuthenticatedExecutiveAuditRoute
  '/_authenticated/executive/workforce': typeof AuthenticatedExecutiveWorkforceRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/settings/agency': typeof AuthenticatedSettingsAgencyRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/governance': typeof AuthenticatedSettingsGovernanceRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/subscription': typeof AuthenticatedSettingsSubscriptionRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/settings/voice': typeof AuthenticatedSettingsVoiceRoute
  '/_authenticated/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/api/public/meet-executive': typeof ApiPublicMeetExecutiveRoute
  '/api/public/meet-request': typeof ApiPublicMeetRequestRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/_authenticated/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/_authenticated/executive/': typeof AuthenticatedExecutiveIndexRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/health/build': typeof ApiPublicHealthBuildRoute
  '/api/public/health/opus-probe': typeof ApiPublicHealthOpusProbeRoute
  '/api/public/hooks/executive-autonomy': typeof ApiPublicHooksExecutiveAutonomyRoute
  '/api/public/hooks/task-engine': typeof ApiPublicHooksTaskEngineRoute
  '/api/public/payments/stripe-webhook': typeof ApiPublicPaymentsStripeWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tmp/env-check': typeof ApiPublicTmpEnvCheckRoute
  '/api/public/tmp/fly-ipv6': typeof ApiPublicTmpFlyIpv6Route
  '/api/public/tmp/fly-verify': typeof ApiPublicTmpFlyVerifyRoute
  '/api/public/voice/events': typeof ApiPublicVoiceEventsRoute
  '/api/public/voice/turn': typeof ApiPublicVoiceTurnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/meet'
    | '/privacy-policy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/settings'
    | '/analytics'
    | '/crm'
    | '/dashboard'
    | '/developer'
    | '/hq'
    | '/profile'
    | '/sales-elite'
    | '/tasks'
    | '/join/$token'
    | '/q/$token'
    | '/conversations/$conversationId'
    | '/executive/$workerKey'
    | '/executive/audit'
    | '/executive/workforce'
    | '/leads/$leadId'
    | '/settings/agency'
    | '/settings/ai'
    | '/settings/api-keys'
    | '/settings/governance'
    | '/settings/notifications'
    | '/settings/subscription'
    | '/settings/team'
    | '/settings/voice'
    | '/settings/whatsapp'
    | '/api/public/meet-executive'
    | '/api/public/meet-request'
    | '/api/public/whatsapp'
    | '/conversations/'
    | '/executive/'
    | '/knowledge/'
    | '/leads/'
    | '/settings/'
    | '/api/public/health/build'
    | '/api/public/health/opus-probe'
    | '/api/public/hooks/executive-autonomy'
    | '/api/public/hooks/task-engine'
    | '/api/public/payments/stripe-webhook'
    | '/api/public/payments/webhook'
    | '/api/public/tmp/env-check'
    | '/api/public/tmp/fly-ipv6'
    | '/api/public/tmp/fly-verify'
    | '/api/public/voice/events'
    | '/api/public/voice/turn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/meet'
    | '/privacy-policy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/analytics'
    | '/crm'
    | '/dashboard'
    | '/developer'
    | '/hq'
    | '/profile'
    | '/sales-elite'
    | '/tasks'
    | '/join/$token'
    | '/q/$token'
    | '/conversations/$conversationId'
    | '/executive/$workerKey'
    | '/executive/audit'
    | '/executive/workforce'
    | '/leads/$leadId'
    | '/settings/agency'
    | '/settings/ai'
    | '/settings/api-keys'
    | '/settings/governance'
    | '/settings/notifications'
    | '/settings/subscription'
    | '/settings/team'
    | '/settings/voice'
    | '/settings/whatsapp'
    | '/api/public/meet-executive'
    | '/api/public/meet-request'
    | '/api/public/whatsapp'
    | '/conversations'
    | '/executive'
    | '/knowledge'
    | '/leads'
    | '/settings'
    | '/api/public/health/build'
    | '/api/public/health/opus-probe'
    | '/api/public/hooks/executive-autonomy'
    | '/api/public/hooks/task-engine'
    | '/api/public/payments/stripe-webhook'
    | '/api/public/payments/webhook'
    | '/api/public/tmp/env-check'
    | '/api/public/tmp/fly-ipv6'
    | '/api/public/tmp/fly-verify'
    | '/api/public/voice/events'
    | '/api/public/voice/turn'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/data-deletion'
    | '/meet'
    | '/privacy-policy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/settings'
    | '/_authenticated/analytics'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/developer'
    | '/_authenticated/hq'
    | '/_authenticated/profile'
    | '/_authenticated/sales-elite'
    | '/_authenticated/tasks'
    | '/join/$token'
    | '/q/$token'
    | '/_authenticated/conversations/$conversationId'
    | '/_authenticated/executive/$workerKey'
    | '/_authenticated/executive/audit'
    | '/_authenticated/executive/workforce'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/settings/agency'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/governance'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/subscription'
    | '/_authenticated/settings/team'
    | '/_authenticated/settings/voice'
    | '/_authenticated/settings/whatsapp'
    | '/api/public/meet-executive'
    | '/api/public/meet-request'
    | '/api/public/whatsapp'
    | '/_authenticated/conversations/'
    | '/_authenticated/executive/'
    | '/_authenticated/knowledge/'
    | '/_authenticated/leads/'
    | '/_authenticated/settings/'
    | '/api/public/health/build'
    | '/api/public/health/opus-probe'
    | '/api/public/hooks/executive-autonomy'
    | '/api/public/hooks/task-engine'
    | '/api/public/payments/stripe-webhook'
    | '/api/public/payments/webhook'
    | '/api/public/tmp/env-check'
    | '/api/public/tmp/fly-ipv6'
    | '/api/public/tmp/fly-verify'
    | '/api/public/voice/events'
    | '/api/public/voice/turn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DataDeletionRoute: typeof DataDeletionRoute
  MeetRoute: typeof MeetRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  JoinTokenRoute: typeof JoinTokenRoute
  QTokenRoute: typeof QTokenRoute
  ApiPublicMeetExecutiveRoute: typeof ApiPublicMeetExecutiveRoute
  ApiPublicMeetRequestRoute: typeof ApiPublicMeetRequestRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
  ApiPublicHealthBuildRoute: typeof ApiPublicHealthBuildRoute
  ApiPublicHealthOpusProbeRoute: typeof ApiPublicHealthOpusProbeRoute
  ApiPublicHooksExecutiveAutonomyRoute: typeof ApiPublicHooksExecutiveAutonomyRoute
  ApiPublicHooksTaskEngineRoute: typeof ApiPublicHooksTaskEngineRoute
  ApiPublicPaymentsStripeWebhookRoute: typeof ApiPublicPaymentsStripeWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTmpEnvCheckRoute: typeof ApiPublicTmpEnvCheckRoute
  ApiPublicTmpFlyIpv6Route: typeof ApiPublicTmpFlyIpv6Route
  ApiPublicTmpFlyVerifyRoute: typeof ApiPublicTmpFlyVerifyRoute
  ApiPublicVoiceEventsRoute: typeof ApiPublicVoiceEventsRoute
  ApiPublicVoiceTurnRoute: typeof ApiPublicVoiceTurnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hq': {
      id: '/_authenticated/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof AuthenticatedHqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-elite': {
      id: '/_authenticated/sales-elite'
      path: '/sales-elite'
      fullPath: '/sales-elite'
      preLoaderRoute: typeof AuthenticatedSalesEliteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversations/': {
      id: '/_authenticated/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthenticatedConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations/$conversationId': {
      id: '/_authenticated/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive/': {
      id: '/_authenticated/executive/'
      path: '/executive'
      fullPath: '/executive/'
      preLoaderRoute: typeof AuthenticatedExecutiveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive/$workerKey': {
      id: '/_authenticated/executive/$workerKey'
      path: '/executive/$workerKey'
      fullPath: '/executive/$workerKey'
      preLoaderRoute: typeof AuthenticatedExecutiveWorkerKeyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive/audit': {
      id: '/_authenticated/executive/audit'
      path: '/executive/audit'
      fullPath: '/executive/audit'
      preLoaderRoute: typeof AuthenticatedExecutiveAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executive/workforce': {
      id: '/_authenticated/executive/workforce'
      path: '/executive/workforce'
      fullPath: '/executive/workforce'
      preLoaderRoute: typeof AuthenticatedExecutiveWorkforceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/agency': {
      id: '/_authenticated/settings/agency'
      path: '/agency'
      fullPath: '/settings/agency'
      preLoaderRoute: typeof AuthenticatedSettingsAgencyRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/governance': {
      id: '/_authenticated/settings/governance'
      path: '/governance'
      fullPath: '/settings/governance'
      preLoaderRoute: typeof AuthenticatedSettingsGovernanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/subscription': {
      id: '/_authenticated/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof AuthenticatedSettingsSubscriptionRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/voice': {
      id: '/_authenticated/settings/voice'
      path: '/voice'
      fullPath: '/settings/voice'
      preLoaderRoute: typeof AuthenticatedSettingsVoiceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/whatsapp': {
      id: '/_authenticated/settings/whatsapp'
      path: '/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AuthenticatedSettingsWhatsappRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/api/public/meet-executive': {
      id: '/api/public/meet-executive'
      path: '/api/public/meet-executive'
      fullPath: '/api/public/meet-executive'
      preLoaderRoute: typeof ApiPublicMeetExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meet-request': {
      id: '/api/public/meet-request'
      path: '/api/public/meet-request'
      fullPath: '/api/public/meet-request'
      preLoaderRoute: typeof ApiPublicMeetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/build': {
      id: '/api/public/health/build'
      path: '/api/public/health/build'
      fullPath: '/api/public/health/build'
      preLoaderRoute: typeof ApiPublicHealthBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/opus-probe': {
      id: '/api/public/health/opus-probe'
      path: '/api/public/health/opus-probe'
      fullPath: '/api/public/health/opus-probe'
      preLoaderRoute: typeof ApiPublicHealthOpusProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/executive-autonomy': {
      id: '/api/public/hooks/executive-autonomy'
      path: '/api/public/hooks/executive-autonomy'
      fullPath: '/api/public/hooks/executive-autonomy'
      preLoaderRoute: typeof ApiPublicHooksExecutiveAutonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/task-engine': {
      id: '/api/public/hooks/task-engine'
      path: '/api/public/hooks/task-engine'
      fullPath: '/api/public/hooks/task-engine'
      preLoaderRoute: typeof ApiPublicHooksTaskEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/stripe-webhook': {
      id: '/api/public/payments/stripe-webhook'
      path: '/api/public/payments/stripe-webhook'
      fullPath: '/api/public/payments/stripe-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmp/env-check': {
      id: '/api/public/tmp/env-check'
      path: '/api/public/tmp/env-check'
      fullPath: '/api/public/tmp/env-check'
      preLoaderRoute: typeof ApiPublicTmpEnvCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmp/fly-ipv6': {
      id: '/api/public/tmp/fly-ipv6'
      path: '/api/public/tmp/fly-ipv6'
      fullPath: '/api/public/tmp/fly-ipv6'
      preLoaderRoute: typeof ApiPublicTmpFlyIpv6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmp/fly-verify': {
      id: '/api/public/tmp/fly-verify'
      path: '/api/public/tmp/fly-verify'
      fullPath: '/api/public/tmp/fly-verify'
      preLoaderRoute: typeof ApiPublicTmpFlyVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice/events': {
      id: '/api/public/voice/events'
      path: '/api/public/voice/events'
      fullPath: '/api/public/voice/events'
      preLoaderRoute: typeof ApiPublicVoiceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice/turn': {
      id: '/api/public/voice/turn'
      path: '/api/public/voice/turn'
      fullPath: '/api/public/voice/turn'
      preLoaderRoute: typeof ApiPublicVoiceTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAgencyRoute: typeof AuthenticatedSettingsAgencyRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsGovernanceRoute: typeof AuthenticatedSettingsGovernanceRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsSubscriptionRoute: typeof AuthenticatedSettingsSubscriptionRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsVoiceRoute: typeof AuthenticatedSettingsVoiceRoute
  AuthenticatedSettingsWhatsappRoute: typeof AuthenticatedSettingsWhatsappRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAgencyRoute: AuthenticatedSettingsAgencyRoute,
    AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
    AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
    AuthenticatedSettingsGovernanceRoute: AuthenticatedSettingsGovernanceRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsSubscriptionRoute:
      AuthenticatedSettingsSubscriptionRoute,
    AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
    AuthenticatedSettingsVoiceRoute: AuthenticatedSettingsVoiceRoute,
    AuthenticatedSettingsWhatsappRoute: AuthenticatedSettingsWhatsappRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedHqRoute: typeof AuthenticatedHqRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSalesEliteRoute: typeof AuthenticatedSalesEliteRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedConversationsConversationIdRoute: typeof AuthenticatedConversationsConversationIdRoute
  AuthenticatedExecutiveWorkerKeyRoute: typeof AuthenticatedExecutiveWorkerKeyRoute
  AuthenticatedExecutiveAuditRoute: typeof AuthenticatedExecutiveAuditRoute
  AuthenticatedExecutiveWorkforceRoute: typeof AuthenticatedExecutiveWorkforceRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedConversationsIndexRoute: typeof AuthenticatedConversationsIndexRoute
  AuthenticatedExecutiveIndexRoute: typeof AuthenticatedExecutiveIndexRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedHqRoute: AuthenticatedHqRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSalesEliteRoute: AuthenticatedSalesEliteRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedConversationsConversationIdRoute:
    AuthenticatedConversationsConversationIdRoute,
  AuthenticatedExecutiveWorkerKeyRoute: AuthenticatedExecutiveWorkerKeyRoute,
  AuthenticatedExecutiveAuditRoute: AuthenticatedExecutiveAuditRoute,
  AuthenticatedExecutiveWorkforceRoute: AuthenticatedExecutiveWorkforceRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedConversationsIndexRoute: AuthenticatedConversationsIndexRoute,
  AuthenticatedExecutiveIndexRoute: AuthenticatedExecutiveIndexRoute,
  AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DataDeletionRoute: DataDeletionRoute,
  MeetRoute: MeetRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  JoinTokenRoute: JoinTokenRoute,
  QTokenRoute: QTokenRoute,
  ApiPublicMeetExecutiveRoute: ApiPublicMeetExecutiveRoute,
  ApiPublicMeetRequestRoute: ApiPublicMeetRequestRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
  ApiPublicHealthBuildRoute: ApiPublicHealthBuildRoute,
  ApiPublicHealthOpusProbeRoute: ApiPublicHealthOpusProbeRoute,
  ApiPublicHooksExecutiveAutonomyRoute: ApiPublicHooksExecutiveAutonomyRoute,
  ApiPublicHooksTaskEngineRoute: ApiPublicHooksTaskEngineRoute,
  ApiPublicPaymentsStripeWebhookRoute: ApiPublicPaymentsStripeWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTmpEnvCheckRoute: ApiPublicTmpEnvCheckRoute,
  ApiPublicTmpFlyIpv6Route: ApiPublicTmpFlyIpv6Route,
  ApiPublicTmpFlyVerifyRoute: ApiPublicTmpFlyVerifyRoute,
  ApiPublicVoiceEventsRoute: ApiPublicVoiceEventsRoute,
  ApiPublicVoiceTurnRoute: ApiPublicVoiceTurnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
